export class User {
  u_id: number;
  u_name: string;
  u_username: string;
  u_password: string;
  u_role_id: number;
  u_role_name: string;
  u_is_admin: string;
  u_active_yn: string;
  u_mother_name: string;
  u_father_name: string;
  u_contact_person: string;
  u_nationality: number;
  u_nationality_name: string;
  u_date_of_birth: number;
  u_gender: number;
  u_gender_name: string;
  u_emp_code: string;
  u_file_no: string;
  u_date_of_join: number;
  u_contact_email: string;
  u_contact_mobile: string;
  u_contact_home: string;
  u_contact_office: string;
  u_contact_address: string;
  u_contact_sim_required: string;
  u_cre_by: number;
  u_cre_by_name: string;
  u_cre_date: string;
  u_visa_from: string;
  u_visa_uid: string;
  u_visa_issue_date: string;
  u_visa_expiry_date: string;
  u_labour_id: string;
  u_labour_issue_date: string;
  u_labour_expiry_date: string;
  u_emid: string;
  u_emid_issue_date: string;
  u_emid_expiry_date: string;
  u_passport_no: string;
  u_passport_issue_date: string;
  u_passport_expiry_date: string;
  u_marital_status: number;
  u_marital_status_name: string;
  u_religion: number;
  u_religion_name: string;
  u_qualification: number;
  u_qualification_name: string;
  u_specialized_in: string;
  u_personal_id: string;
  u_payment_method:number;
  u_payment_method_name: string;
  u_account_no: string;
  u_uae_exchange_branch: number;
  u_uae_exchange_branch_name: string;
  u_basic_salary: number;
  u_allowance: number;
  u_over_time: number;
  u_present_salary: number;
  u_benefits_after: number;
  u_benefits_after_name: string;
  u_c_id:number;
  u_c_name:string;
  u_ds_id:number;
  u_ds_name:string;

  constructor() {
    this.u_id = 0;
    this.u_name = '',
    this.u_username = '';
    this.u_password = '';
    this.u_role_id = 0;
    this.u_role_name = '';
    this.u_is_admin = '';
    this.u_active_yn = '';
    this.u_mother_name = '';
    this.u_father_name = '';
    this.u_contact_person = '';
    this.u_nationality= 0;
    this.u_nationality_name= '';
    this.u_date_of_birth = 0;
    this.u_gender= 0;
    this.u_gender_name= '';
    this.u_emp_code = '';
    this.u_file_no = '';
    this.u_date_of_join = 0;
    this.u_contact_email = '';
    this.u_contact_mobile = '';
    this.u_contact_home = '';
    this.u_contact_office = '';
    this.u_contact_address = '';
    this.u_contact_sim_required = 'false';
    this.u_cre_by = 0;
    this.u_cre_by_name = '';
    this.u_cre_date = '';
    this.u_visa_from = '';
    this.u_visa_uid = '';
    this.u_visa_issue_date = '';
    this.u_visa_expiry_date = '';
    this.u_labour_id = '';
    this.u_labour_issue_date = '';
    this.u_labour_expiry_date = '';
    this.u_emid = '';
    this.u_emid_issue_date = '';
    this.u_emid_expiry_date = '';
    this.u_passport_no = '';
    this.u_passport_issue_date = '';
    this.u_passport_expiry_date = '';
    this.u_marital_status= 0;
    this.u_marital_status_name= '';
    this.u_religion_name='';
    this.u_religion = 0;
    this.u_qualification = 0;
    this.u_qualification_name='';
    this.u_specialized_in = '';
    this.u_personal_id = '';
    this.u_payment_method= 0;
    this.u_payment_method_name= '';
    this.u_account_no = '';
    this.u_uae_exchange_branch= 0;
    this.u_uae_exchange_branch_name= '';
    this.u_basic_salary= 0;
    this.u_allowance = 0;
    this.u_over_time = 0;
    this.u_present_salary = 0;
    this.u_benefits_after=0;
    this.u_benefits_after_name='';
    this.u_c_id=0;
    this.u_c_name='';
    this.u_ds_id=0;
    this.u_ds_name='';

  }

}
